# Generated by Django 5.0.6 on 2025-11-17 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField(blank=True, help_text='Age in years', null=True)),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner - New to fitness'), ('intermediate', 'Intermediate - Regular exercise'), ('advanced', 'Advanced - Experienced athlete')], max_length=20)),
                ('fitness_goals', models.TextField(help_text='Selected fitness goals (comma-separated)')),
                ('additional_goals', models.TextField(blank=True, help_text='Any other fitness goals or details')),
                ('current_frequency', models.CharField(choices=[('none', 'Not currently exercising'), ('1-2', '1-2 times per week'), ('3-4', '3-4 times per week'), ('5+', '5+ times per week')], max_length=10)),
                ('injuries_limitations', models.TextField(blank=True, help_text='Any injuries, health conditions, or physical limitations')),
                ('message', models.TextField(blank=True, help_text="Tell us more about your goals and what you're looking for")),
                ('referral_source', models.CharField(blank=True, help_text='How did you hear about us?', max_length=200)),
                ('group', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client')], default='lead', help_text='Lead or Client status', max_length=10)),
                ('lead_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('denied', 'Denied/Spam')], default='pending', help_text='Status when in lead group', max_length=20)),
                ('client_status', models.CharField(blank=True, choices=[('contacted', 'Contacted - Agreed but Not Paid'), ('active', 'Active - Currently Paying'), ('inactive', 'Inactive - Previously Paid')], help_text='Status when in client group', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for trainer')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When lead was reviewed', null=True)),
                ('reviewed_by', models.CharField(blank=True, help_text='Admin who reviewed', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When lead was approved to become client', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Inquiry',
                'verbose_name_plural': 'Client Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services')], max_length=50)),
                ('identifier', models.SlugField(help_text='Unique identifier for this content block', max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('order', models.IntegerField(default=0, help_text='Display order on the page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'ordering': ['page', 'order'],
                'unique_together': {('page', 'identifier')},
            },
        ),
    ]
